spring:
  application:
    name: TransCom
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.xml
  main:
    banner-mode: off
