spring:
  application:
    name: TransCom
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
    url: ${URL}
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true
  main:
    banner-mode: off
  messages:
    basename: i18n/messages_en.properties
logging:
  level:
    liquibase.ui: WARN
    liquibase.executor: ERROR
