INSERT INTO truck_types (short_name, full_name, length_meters, capacity_cubic_units, image_truck_type_name)
VALUES ('DRYV', 'Dry Van', 16.0, 50.0, 'https://example.com/dry_van.jpg'),
       ('VAN', 'Standard Van', 14.0, 40.0, 'https://example.com/van.jpg'),
       ('CITYVAN', 'City Van', 6.0, 3.0, 'https://example.com/city_van.jpg'),
       ('CURT', 'Curtain Side Trailer', 18.0, 55.0, 'https://example.com/curtain_side.jpg'),
       ('TAIL', 'Tail Lift Trailer', 15.0, 48.0, 'https://example.com/tail_lift.jpg'),
       ('FLAT', 'Flatbed', 17.0, 60.0, 'https://example.com/flatbed.jpg'),
       ('MOVE', 'Moving Floor', 15.0, 55.0, 'https://example.com/moving_floor.jpg'),
       ('STEP', 'Step Deck Trailer', 18.5, 65.0, 'https://example.com/step_deck.jpg'),
       ('LOWB', 'Lowboy Trailer', 13.0, 45.0, 'https://example.com/lowboy.jpg'),
       ('DBLE', 'Double Drop Trailer', 20.0, 70.0, 'https://example.com/double_drop.jpg'),
       ('EXTD', 'Extendable Flatbed Trailer', 22.0, 75.0, 'https://example.com/extendable_flatbed.jpg'),
       ('CONT', 'Container Truck', 12.0, 50.0, 'https://example.com/container_truck.jpg'),
       ('SIDE', 'Side Wall Trailer', 14.0, 55.0, 'https://example.com/side_wall.jpg'),
       ('FBVS', 'Flat Body with Vertical Sides', 16.0, 50.0, 'https://example.com/flat_body_vertical_sides.jpg'),
       ('REFR', 'Refrigerated Trailer', 16.0, 45.0, 'https://example.com/refrigerated_trailer.jpg'),
       ('REEF', 'Reefer Trailer', 17.0, 50.0, 'https://example.com/reefer_trailer.jpg'),
       ('INSU', 'Insulated Trailer', 16.0, 47.0, 'https://example.com/insulated_trailer.jpg'),
       ('MCTR', 'Multicar Trailer', 18.0, 55.0, 'https://example.com/multicar_trailer.jpg'),
       ('CARR', 'Car Hauler', 17.0, 50.0, 'https://example.com/car_hauler.jpg'),
       ('DUMP', 'Dump Truck', 12.0, 40.0, 'https://example.com/dump_truck.jpg'),
       ('TANK', 'Tank Trailer', 15.0, 60.0, 'https://example.com/tank_trailer.jpg'),
       ('EDIB', 'Tank for Edible Liquids', 14.0, 50.0, 'https://example.com/tank_edible_liquids.jpg'),
       ('CHEM', 'General Chemical Trailer', 15.0, 55.0, 'https://example.com/general_chemical_trailer.jpg'),
       ('FUEL', 'Fuel Tanker', 13.0, 45.0, 'https://example.com/fuel_tanker.jpg'),
       ('LNGG', 'LNG/LPG Gas Tank Truck', 14.0, 52.0, 'https://example.com/lng_lpg_truck.jpg'),
       ('CYLN', 'Gas Cylinder Truck', 12.0, 40.0, 'https://example.com/gas_cylinder_truck.jpg'),
       ('BTMN', 'Bitumen Tank Trailer', 16.0, 50.0, 'https://example.com/bitumen_tank_trailer.jpg'),
       ('FISH', 'Fish Carrier', 14.0, 48.0, 'https://example.com/fish_carrier.jpg'),
       ('LFIS', 'Live Fish Carrier', 14.0, 48.0, 'https://example.com/live_fish_carrier.jpg'),
       ('POLE', 'Pole Type Trailer', 18.0, 60.0, 'https://example.com/pole_type_trailer.jpg'),
       ('LOGG', 'Logging Truck', 17.0, 55.0, 'https://example.com/logging_truck.jpg'),
       ('TIMB', 'Timber Lorry', 17.0, 55.0, 'https://example.com/timber_lorry.jpg'),
       ('DRBK', 'Dry Bulk Trailer', 16.0, 50.0, 'https://example.com/dry_bulk_trailer.jpg'),
       ('CEMT', 'Cement Tank Trailer', 15.0, 48.0, 'https://example.com/cement_tank_trailer.jpg');
